### ISSUE TITLE
Unificar Classes CSS

### ISSUE THREAD

**Issue by pereirawe** [Solon-Santos-dev/Landing-Pessoal#2]
Nas etiquetas HTML, pode utilizar a propriedade class e id.
As duas são muito uteis porem com objetivos diferentes.
No CSS tem muito código repetido porque não está aproveitando as classes do jeito certo.

https://www.alura.com.br/artigos/qual-diferenca-entre-id-e-class

![image](https://user-images.githubusercontent.com/5939144/206808530-011900f2-2202-4ef4-8e30-3f1a7a0437a3.png)

**Comment by Solon-Santos-dev** [comment]
Excelente, farei isso. Te enviei algumas dúvidas que surgiram, depois me dá um feedback.
