### ISSUE TITLE
Uniformidade nos botoes

### ISSUE THREAD

**Issue by pereirawe** [Solon-Santos-dev/Landing-Pessoal#4]
Os botoes estão com estilos diferentes. Sugiro aumentar o padding para o texto não ficar tão na borda, ou reduzir o border-radius

![image](https://user-images.githubusercontent.com/5939144/206808144-5a4878ea-429d-4ade-9677-988122540fcb.png)

![image](https://user-images.githubusercontent.com/5939144/206808964-a2dc9a71-84f7-453d-8313-f98781d6f56b.png)

**Comment by Solon-Santos-dev** [comment]
Feito!
